### PR TITLE
Add priorityClassName to server, worker, scheduler and migration pods

### PR DESCRIPTION
**Pull request by sabyrzhan**
Add priorityClassName to server, worker, scheduler and migration pods to assign custom priority values

### CODE REVIEW

**Review by frivoire — APPROVED** [review]
Quick review (I didn't test it): it looks nice and clean 👍

**Comment by frivoire** [comment]
> @frivoire hey, is there any way to review and merge this PR?

I've reviewed it, but I'm not a maintainer of this repo, just a contributor (who got a PR merged in the paste).
So I can't help you more here, sorry.

**Comment by justinclift** [comment]
@frivoire If you're interested (?) I'm happy to give you maintainer access to this repo. :smile:

**Comment by justinclift** [comment]
Done. :smile:

**Comment by justinclift** [comment]
Done. :smile:

**Pull request merged**
