### PR TITLE
fix chart installation within a namespace with istio-injection enabled

### LINKED ISSUE #48: installation error within namespace with istio-injection enabled and helm flags atomic, cleanup_on_fail
hello guys,

thanks for the chart.

I've the following namespace available -
```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    istio-injection: enabled
```

all components work correctly other than [hook-install-job](https://github.com/getredash/contrib-helm-chart/blob/master/templates/hook-install-job.yaml)

The job finished up correctly and exits, sidecar keeps on going while the pod moves into `NotReady` status and would uninstall if installed with atomic and cleanup_on_fail option
A similar issue occurred while running tekton-pipelines. The workaround is to add `sidecar.istio.io/inject: "false"` to pod annotations.
specifically, at
https://github.com/getredash/contrib-helm-chart/blob/dc065e5d4069967b19ec9d768479166b183b0bdb/templates/hook-install-job.yaml#L15

and also probably in upgrade job as well
https://github.com/getredash/contrib-helm-chart/blob/dc065e5d4069967b19ec9d768479166b183b0bdb/templates/hook-upgrade-job.yaml#L15

the chart doesn't have configurable annotations for these jobs.

Alternatively, I'm making it work by installing the chart in a different `namespace` with istio-injection disabled and manually configure `podAnnotations` for all the deployment sub components which are configurable.

Thank you!

### PR DESCRIPTION
**Pull request by aakashRajur**
* 666ebae adds missing fields to extend values on installl and upgrade job
* 255e2fa adds before-hook-creation
* be6d518 adds `ttlSecondsAfterFinished` field

### CODE REVIEW

**Comment by grugnog** [comment]
@aakashRajur I think these changes all make sense - I would prefer to review them as separate PRs if that would be OK, though.

**Comment by thodquach** [comment]
Hello @aakashRajur, 
It 's better if we put default annotations for install and upgrade job:
Install:
```
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
```
Upgrade:
```
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
```
I think both `before-hook-creation` and `hook-succeeded` `hook-delete-policy` are needed. For now, the `master branch` only support `hook-succeeded`.

**Comment by aakashRajur** [comment]
> Hello @aakashRajur,
> It 's better if we put default annotations for install and upgrade job in values.yaml:
> Install:
> 
> ```
>     "helm.sh/hook": post-install
>     "helm.sh/hook-weight": "-5"
>     "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
> ```
> 
> Upgrade:
> 
> ```
>     "helm.sh/hook": post-upgrade
>     "helm.sh/hook-weight": "-5"
>     "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
> ```
> 
> I think both `before-hook-creation` and `hook-succeeded` `hook-delete-policy` are needed. For now, the `master branch` only support `hook-succeeded`.

assuming we need the logs of only latest job, addressed in 255e2fa

**Comment by aakashRajur** [comment]
> @aakashRajur I think these changes all make sense - I would prefer to review them as separate PRs if that would be OK, though.

updated as per your preference, will raise a separate PR

**Comment by aakashRajur** [comment]
hey @grugnog, any updates?

**Comment by grugnog** [comment]
@aakashRajur thanks - this looks good, thank you! I rebased and will merge once tests pass.

**Pull request merged**
