### PR TITLE
Update chart dependencies

### PR DESCRIPTION
**Pull request by ArcticXWolf**
I have updated the postgresql and redis dependencies of this chart.

This introduced a breaking change for the postgresql credentials/secret:
1. Helm values.yaml changes from `postgresql.postgresqlUsername` -> `postgresql.auth.username`
2. Helm values.yaml changes from `postgresql.postgresqlPassword` -> `postgresql.auth.password`
3. Helm values.yaml changes from `postgresql.postgresqlDatabase` -> `postgresql.auth.database`
4. The key of the postgresql password secret changed from `postgresql-password` to `password`

So we need to do two things before merge and I would like to have your opinion on this:
1. How do we deal and communicate the breaking changes?
2. Update chart version number

### CODE REVIEW

**Comment by masayuki038** [comment]
@grugnog I failed to launch Redash with this helm and added my comment to https://github.com/getredash/contrib-helm-chart/issues/145. Could you check this PR ?

**Comment by masayuki038** [comment]
@grugnog ping

**Comment by ArcticXWolf** [comment]
[Copied from issue #145]
@masayuki038 I dont see any further activity on this repo, so you probably have to fork and use my PR code to get it to work. Just as a headsup: if you want to use my PR, then you need to change your values.yaml keys a bit. I've detailed the changes in the PR description :) Hope it helps a bit!

**Comment by masayuki038** [comment]
@justinclift Can you check this if you have some time?

**Comment by justinclift** [comment]
@masayuki038 I don't really have any clue with Helm, so can't directly help here.

That being said, it looks like @ArcticXWolf might be interested in helping out with this repo?

As in, potentially adding as a member to enable fixing/updating/etc stuff.  @ArcticXWolf is that your kind of thing? :smile:

**Comment by ArcticXWolf** [comment]
Sorry, we only tested Redash for a short time and do not use it anymore. I just happened to fix this issue during experimentation. So sadly I wont have time to tend to this repo.

**Comment by justinclift** [comment]
@ArcticXWolf No worries. :smile:

**Comment by justinclift** [comment]
@AndrewChubatiuk it can be done, but the person will need to have a clear history of competency in the pieces involved. :smile:

**Comment by justinclift** [comment]
Well, your GitHub profile seems to be complete private.  So it's super hard to tell what you're into, what you're good at, look at how well you interact with others, and that kind of thing. :frowning:

**Comment by AndrewChubatiuk** [comment]
@justinclift my profile should be public now

**Comment by justinclift** [comment]
@AndrewChubatiuk Cool.  Looking over some of your activity for the last several years, it looks legit rather than dodgy.  So, no worries from me now. :smile:

**Comment by justinclift** [comment]
@grugnog Are you ok with @AndrewChubatiuk being added as a maintainer for this repo? :smile:

**Comment by justinclift** [comment]
@AndrewChubatiuk If we don't get a response in a few days, we can just go ahead and add you as a maintainer. :wink:

**Comment by justinclift** [comment]
@AndrewChubatiuk Heh Heh Heh, I nearly forgot about this.

As we've not heard anything from @grugnog, I've just sent you an invite for this repo so you can do stuff in it. :smile:

**Comment by AndrewChubatiuk** [comment]
@justinclift could you please provide me more access in a repo? I want to replace circleci with github actions

**Comment by AndrewChubatiuk** [comment]
closing this PR as it's covered in #158

**Comment by justinclift** [comment]
> could you please provide me more access in a repo?

@AndrewChubatiuk Oops, I missed that message.  Is this something you still need me to look into?

**Pull request closed without merging**
