### PR TITLE
Allow to specify envFrom secret

### PR DESCRIPTION
**Pull request by qiq**
When `externalPostgreSQL` is used, password must be specified in the value file (as a part of the connection string). This is not desirable in case value files are persisted in git.

This PR adds a possibility to set environment variables from a secret (using envFrom, see https://kubernetes.io/docs/tasks/inject-data-application/distribute-credentials-secure/#configure-all-key-value-pairs-in-a-secret-as-container-environment-variables). Then, environment variable may be referenced in the value file, e.g.: `postgresql://user:$(POSTGRESQL_PASSWORD)@host:5432/database`.

`envSecretName` value key is used to specify secret with environment variables.

### CODE REVIEW

**Comment by rodrigoscna** [comment]
Is there any estimate on when is this getting released? I think it's the only missing piece for me to deploy on my cluster without "leaking" any passwords into git

**Comment by grugnog** [comment]
@rodrigoscna this should be in v2.1.0

**Comment by grugnog** [comment]
@qiq @rodrigoscna if you have a sec, could you take a look at the thread in #57? The envFrom secret approach seems a little opaque and it's not totally clear how it works. I am wondering about depreciating this (for removal in a couple of major versions) and going with the more declarative approach in that PR, but want to make sure that approach would work for you also?

**Comment by rodrigoscna** [comment]
@grugnog Yeah! That approach works for me and looks even clearer than the `envSecretName` one.
I`ll switch to that when it gets released!

**Comment by qiq** [comment]
I agree, externalSecret is fine for me.

**Pull request merged**
