### PR TITLE
Add liveness check for workers

### LINKED ISSUE #72: readiness + liveness for worker
The adhocworker and scheduledworker deployments are missing a proper readiness and/or liveness check. This leads to unresponsive containers in the case where redis connections get closed.

```
[2021-01-27 14:22:04,485][PID:6][WARNING][MainProcess] consumer: Connection to broker lost. Trying to re-establish the connection...
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 318, in start
    blueprint.start(self)
  File "/usr/local/lib/python2.7/site-packages/celery/bootsteps.py", line 119, in start
    step.start(parent)
  File "/usr/local/lib/python2.7/site-packages/celery/worker/consumer/consumer.py", line 596, in start
    c.loop(*c.loop_args())
  File "/usr/local/lib/python2.7/site-packages/celery/worker/loops.py", line 91, in asynloop
    next(loop)
  File "/usr/local/lib/python2.7/site-packages/kombu/asynchronous/hub.py", line 362, in create_loop
    cb(*cbargs)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 1052, in on_readable
    self.cycle.on_readable(fileno)
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 348, in on_readable
    chan.handlers[type]()
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 679, in _receive
    ret.append(self._receive_one(c))
  File "/usr/local/lib/python2.7/site-packages/kombu/transport/redis.py", line 690, in _receive_one
    response = c.parse_response()
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 3036, in parse_response
    return self._execute(connection, connection.read_response)
  File "/usr/local/lib/python2.7/site-packages/redis/client.py", line 3013, in _execute
    return command(*args)
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 637, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 290, in read_response
    response = self._buffer.readline()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 224, in readline
    self._read_from_socket()
  File "/usr/local/lib/python2.7/site-packages/redis/connection.py", line 199, in _read_from_socket
    (e.args,))
ConnectionError: Error while reading from socket: (u'Connection closed by server.',)
```
I think the best would be to crash the containers whenever those errors occur otherwise the liveness-check should report an error.

### PR DESCRIPTION
**Pull request by shubhwip**
closes #72

Dependent on PR https://github.com/getredash/redash/pull/5886 and it is merged already.

## Related Issues : 
https://github.com/getredash/redash/issues/5885
https://github.com/getredash/contrib-helm-chart/issues/124
https://github.com/getredash/contrib-helm-chart/issues/72
https://github.com/getredash/redash/issues/5801

## More context
liveness check is based on
rq info command returns monitoring status of redash workers and other status checks
Sample Output
```
redash@redash-adhocworker-778fc5dbb6-jpscq:/app$ rq info --url $REDASH_REDIS_URL -R
queries      | 0
default      | 2
periodic     |██████████████████ 748
emails       | 0
schemas      | 0
5 queues, 750 jobs total

queries:  1a6d953d53984424ab775d3647427e7b (idle), 29dbf1ec1f774bacbd91ca36ccef6e43 (idle)
default:  –
periodic: –
emails:   –
schemas:  –
2 workers, 5 queues
```

### CODE REVIEW

**Comment by shubhwip** [comment]
@grugnog can you please check this PR ? This issue has been reported by many. 
We can remove default values(in case PR on redash repo doesn't get merged) and get it merged and people who are using this helm charts can supply their own values with liveness checks.

**Comment by grugnog** [comment]
@shubhwip we will need to [add the new values to the README](https://github.com/getredash/contrib-helm-chart/blob/master/CONTRIBUTING.md#pre-commit-hook-setup) but otherwise this looks good to me. We don't want to break installs though, so I don't think we should merge until upstream is merged however, and we can't release until upstream is released.

**Comment by shubhwip** [comment]
@grugnog Thank you so much for your feedback.
While we wait for the upstream to merge first,  Can we comment down the liveness values defined in `values.yaml` and merge this so that helm users can override liveness check by themselves in the meantime ? 
If we agree on this then I can put those changes otherwise we wait for the upstream to get the changes merged first.

**Comment by shubhwip** [comment]
@grugnog made the changes as requested and now upstream is merged.

**Comment by aneagoe** [comment]
Would love to see this merged; currently facing issues with workers silently dying and we can only manually bounce them.

**Comment by shubhwip** [comment]
@grugnog when do you plan to merge the changes as upstream changes are merged months ago :) ?

**Comment by ffzzhong** [comment]
@grugnog please kindly take a look

**Comment by grugnog** [comment]
@shubhwip @ffzzhong it's merged upstream, but still no stable release to point at - I can try and get a preview release up that folks can try, but I would be wary in terms of upgrade path.

**Comment by justinclift** [comment]
Now that Redash is a Community led project, we've been madly working through the outstanding PRs, Dependabot issues, (etc) getting things cleaned up and ready for a next release.

It's going to be a few weeks away though.  We *might* be able to get something like an "Redash 11.0.0 *alpha 1*" (or beta) out the door in a fortnight or so, but we'll see. :smile:

**Comment by justinclift** [comment]
@grugnog If you want to create some kind of preview release for people to do with in the meantime, then please feel encouraged to do so.  It could be considered a good initial shake out to see if we've busted anything non-obvious in the mad rush of merging PRs and similar. :smile:

**Comment by grugnog** [comment]
That sounds good - I am working on getting the other PRs tested and merged, then will look at this

**Review by alifaraj01 — APPROVED** [review]

**Comment by madbbb** [comment]
@shubhwip thanks for your PR! can you share how you implemented `/app/bin/docker-entrypoint workers_healthcheck` please?

**Comment by justinclift** [comment]
@AndrewChubatiuk Does this PR seem sensible to you?

**Pull request merged**
