### PR TITLE
WIP: Changes required for redash v9

### PR DESCRIPTION
**Pull request by jimsparkman**
This is a WIP upgrade to the chart to support v9 (currently in beta). There are a number of small changes to how workers process queues (now RQ instead of celery).

Additionally, the current beta release has a bug which causes the hook install and upgrade jobs to fail. I've submitted https://github.com/getredash/redash/pull/4989 which resolves this issue. It has been accepted and the fix should be in the next beta release.

In the mean time, you can deploy this with the current beta image, understanding that the jobs will fail (but the deployment will work just fine). There are no schema migrations from v8->v9, so this drops in easily.

### CODE REVIEW

**Comment by samfitz66** [comment]
Hi - any updates on this?

**Comment by jimsparkman** [comment]
I've been running this in production in my company for over a year now. Not really sure what is up with v9 of redash and when it'll go officially.

**Comment by grugnog** [comment]
I am open to merging this if it can be made backwards compatible with v8 - otherwise I think we need to wait until v9 is released (or at least a RC) so we can test a stable upgrade path.

**Comment by bratao** [comment]
Any chance of this going thru now that V10 is near to be released?

**Comment by bmtKIA6** [comment]
From what I can tell, v10 is similar in architecture (rq). 
Does it take much to move it to v10? Is it a matter of updating the tag version?

**Comment by bmtKIA6** [comment]
> From what I can tell, v10 is similar in architecture (rq).
> Does it take much to move it to v10? Is it a matter of updating the tag version?

Looks like this works with v10, at the time of writing 'preview' is the latest image tag for v10.

**Comment by mogggggg** [comment]
v10 was just recently released! 🎉
Can we get this merged in soon?

**Comment by grugnog** [comment]
I think this PR needs a bit of work, since both the chart and Redash (since v9 beta) have a number of changes we need to accommodate and test. I won't have time to work on these for a few weeks most likely (I am not affiliated with Redash and need to balance this with other commitments) - I should have time to review a PR if someone else has time/skills though.

**Comment by grugnog** [comment]
Closing in favor of #103

**Pull request closed without merging**
